import{a as m,i as f,S as h}from"./assets/vendor-D0cagnvz.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const p=async(t,r)=>{const a="49047505-943fdeb799f69f50e2a05df2c",o="https://pixabay.com/api/";try{const e=await m.get(o,{params:{key:a,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}});return{images:e.data.hits,totalHits:e.data.totalHits}}catch(e){return console.log("Error fetching images:",e),{images:[],totalHits:0}}},y=t=>{const r=document.querySelector(".gallery");if((t==null?void 0:t.length)===0){f.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}t.forEach(o=>{const e=document.createElement("div");e.classList.add("image-card"),e.innerHTML=`
      <a href="${o.largeImageURL}" class="gallery-link">
        <img src="${o.webformatURL}" alt="${o.tags}" class="gallery-image" />
      </a>
      <div class="image-info">
        <p><strong>Likes</strong> <span>${o.likes}</span></p>
        <p><strong>Views</strong> <span>${o.views}</span></p>
        <p><strong>Comments</strong> <span>${o.comments}</span></p>
        <p><strong>Downloads</strong> <span>${o.downloads}</span></p>
      </div>
    `,r.appendChild(e)}),new h(".gallery a").refresh()},L=()=>{document.querySelector(".loader").classList.add("active")},b=()=>{document.querySelector(".loader").classList.remove("active")};let l="",n=1,d=0;const g=document.querySelector(".form"),v=g.querySelector('input[type="text"]'),w=document.querySelector(".gallery"),c=document.querySelector("#load-more-button"),u=document.querySelector(".loader");g.addEventListener("submit",async t=>{if(t.preventDefault(),l=v.value.trim(),!l)return;n=1,L(),c.style.display="none",u.style.display="block",w.innerHTML="";const{images:r,totalHits:a}=await p(l,n);y(r),d=a,b(),u.style.display="none",c.style.display="block"});c.addEventListener("click",async()=>{n++;const{images:t,totalHits:r}=await p(l,n);y(t),d=r,n*15>=d&&(c.style.display="none",alert("We're sorry, but you've reached the end of search results.")),S()});const S=()=>{const t=document.querySelector(".image-card").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
